<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-L326B3C6" failures="2" tests="2" name="Test(failed)" time="0.278" errors="0" timestamp="2024-08-27T14:03:18 IST">
  <testcase classname="TestNgExecuteFailedTestCases.FailedTestCaseExample" name="TestCase02" time="0.074">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgExecuteFailedTestCases.FailedTestCaseExample.TestCase02(FailedTestCaseExample.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="TestNgExecuteFailedTestCases.FailedTestCaseExample" name="TestCase01" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNgExecuteFailedTestCases.FailedTestCaseExample.TestCase01(FailedTestCaseExample.java:8)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="TestNgExecuteFailedTestCases.FailedTestCaseExample" name="TestCase03" time="0.0">
    <ignored/>
  </testcase> <!-- TestCase03 -->
</testsuite> <!-- Test(failed) -->
